### ISSUE TITLE
FSX compatibility lost since 2013/05/29

### ISSUE THREAD

**Issue by g6r6e6g** [cybereality/Perception#32]
Hi contributors,

I used vireio Perception with FSX and the rift, the 2013 May29 release is running well, but every release after that date do not work (eg. the 2013 Jun07), FSX hang up on black screen.
I can t figure out which update is responsible of.
Any suggests ?

Thanks.

**Comment by baggyg** [comment]
I realise this is an old issue. We have currently stopped investigating this due to the excellent looking DCOC mod that is promised to appear anytime now, which should be far better than VP can support this game.
