### ISSUE TITLE
How to add on VRboost support for a new game?

### ISSUE THREAD

**Issue by luxuchenghu** [cybereality/Perception#50]
The game's name is "Mount&Blade Warband", and it is not supported in the list yet. I am wondering how to add on VRboost support for it. 
It seems a "mb_warband.xml" is required  in "/cfg/VRboost_rules". 
I found "VRboostReferee.exe" can turn a "*.xml" to "*.MTBS", VRboost can use *.MTBS and perception can parse *.xml. But what exactly is  *.MTBS? Why can not we just use xml?

Is there any steps could be followed to add on VRboost support for a new game?

Thank you very much for your great help!

**Comment by baggyg** [comment]
The first step is to become proficient with Cheat Engine (http://www.cheatengine.org/). Download this and follow the inbuilt tutorials. You want to get proficient at finding the pitch and yaw at the very least. Once you are good at this, run the games multiple times and after multiple restarts and send a list of memory addresses the yaw / pitch resides in. We can then help build a scanner file.
