### ISSUE TITLE
Bottom parts of menus inaccessible

### ISSUE THREAD

**Issue by jimrandomh** [cybereality/Perception#51]
Using latest version from git, 19-Mar-2015, which identifies itself as version 2.1.5. In Skyrim, when you open menus with Ctrl+Q, only the first 10 menu items are visible. If you highlight the item in the 11th or later position, it shows a red selection marker surrounding empty space; no text is visible.

**Comment by baggyg** [comment]
The latest has a few bugs in I found last night and is not recommended for use. However this behavior is know and actually intentional. I suspect you have the GUI / HUD set on a smaller setting. Set them both to full and you should see all the items

**Comment by jimrandomh** [comment]
No, that's not it; I'm referring to is the Vireio menus, not the game menus, and those don't respond to the GUI/HUD settings at all.

**Comment by baggyg** [comment]
Can you post a screenshot and I will have a look and diagnose?

**Comment by baggyg** [comment]
You are right that the GUI/HUD don't affect the Vireio menus directly however they do restrict the viewport height that the menu can draw into. This means that if the menu is too long it won't be drawn.

**Comment by jimrandomh** [comment]
Here's a screenshot showing the issue:

![truncatedmenu](https://cloud.githubusercontent.com/assets/101191/6766033/a06e1b9e-cfcc-11e4-8b2e-8bf400ac6f85.jpg)

This screenshot was taken in 2.1.3. The issue appears replicable in v2.1.3 and later (also tested 2.1.4 and git-head), but not in v2.1.2 or earlier. GUI and HUD settings do not seem to affect the menu's size, nor where the truncation happens.

**Comment by jimrandomh** [comment]
This doesn't reproduce for me in the current git-head; I'm not sure how or when it got fixed, but the menu code has changed a lot recently so I assume it is.

**Comment by jimrandomh** [comment]
I figured out what causes this: It happens when the game's resolution is smaller than 1920x1080. The menu gets drawn into a back-buffer with the same size as the eye-buffers, with everything assuming it's a 1920x1080 buffer, then scaled on transfer. That buffer should always be 1920x1080, rather than eye buffer-sized.
