### ISSUE TITLE
Position-tracking offsets are rotated by eye convergence angles

### ISSUE THREAD

**Issue by jimrandomh** [cybereality/Perception#53]
Here's an experiment you can do, which demonstrates an issue in position tracking. First, crank up the position-tracking multiplier to a large value (10+), to exaggerate the effect. (This makes small head translations equivalent to walking across the room). Turn towards a distant game object with some depth and detail. Lean back, reset orientation with Shift+R, then lean forward until the object is close to the camera. The two eye views will have a separation that is much too large, proportional to the size of the translation divided by the configured convergence distance.

(Tested in Skyrim, 2.1.4, DK2.)

**Comment by jimrandomh** [comment]
Some googling suggests that convergence shouldn't actually be a thing; it's used for 3D monitors, but for HMDs, the recommendation is that eye rays be parallel, which is equivalent to putting the convergence at infinity. Presently, the convergence is limited to a range which does not go up that high; you have to have at least a little convergence. Which seems like a bug.

Getting rid of convergence entirely seems like the right thing to do, and it'd also fix the interaction with translation.

**Comment by baggyg** [comment]
Don't forget that Vireio Perception is not just a Oculus Rift driver. It can be used on various devices including used as a standard 3D driver (using SBS / OU / Checkerboard). I will defer the question of positional to Simon (Dr Beef), but convergence are needed for those devices and therefore cannot be removed.

**Comment by jimrandomh** [comment]
Mooted by head versions with convergence removed for HMDs. As far as I know 3D monitors aren't commonly used with head tracking, and those are the only things that need convergence.
