### ISSUE TITLE
Pixel-shader roll rotates position-tracking

### ISSUE THREAD

**Issue by jimrandomh** [cybereality/Perception#57]
If the roll mode is set to "pixel shader", then the position-tracking offset is effectively rotated by the roll angle in the XY plane. In other words: if you roll your head 90 degrees, then moving your head left/right relative to the tracking camera moves the in-game camera up/down instead.

**Comment by DrBeef** [comment]
OK, I've fixed it, will put the fix into the merge branch (as that is what
I currently have locally) so it will be applied when your changes are
subsequently merged to the master.
