### ISSUE TITLE
TrackIR support

### ISSUE THREAD

**Issue by samaust** [cybereality/Perception#75]
Perception supports many trackers. Is TrackIR is supported ?

I've got a TrackIR tracker I bought more than 8 years ago (I'm not sure which model it is) with a TrackClip Pro I added later. In a previous personal project I worked on eight years ago, I added TrackIR support using the Optitrack SDK that was available at the time. I'm now on Windows 10. I recently reinstalled that SDK (I still had the installer) and tried my old tracker code and it still works.

Now, I'm wondering :
- Can we use this old Optitrack SDK with the project to add TrackIR support ?
- Is that SDK or a more recent version still available for download (the installer file I have is named "OptiTrack_1.3.035.exe")?
- Does it work with more recent versions of TrackIR ?
- Are there any licensing issues with using this SDK in Perception ?

I think NaturalPoint also have their own SDK that give you more control. The Optitrack SDK just returns three angles and three displacements. I haven't seen the NaturalPoint SDK but I assume that it also applies the curves you set in their software that give you more control. You have to email them or call them to get a copy of their SDK so they don't seem very open about sharing it with developpers.
Does anyone know if :
- They share their SDK for free ?
- Do you have to sign some type of NDA to get a copy of their SDK ?
- Can their SDK be used in an open source project (Perception specifically) ?

**Comment by baggyg** [comment]
Hi, 

You can use TrackIR currently with the project although the method is a bit long winded. You can utilise the SharedMemoryTracker which basically means there is a reserved portion of memory that Vireio reads and another program writes to. For trackIR I had this working using FreePIE which supports it. Basically FreePIE needs to be running a script that reads the values from TrackIR and then writes them to the shared memory tracker (The sharedMemoryTracker DLL needs to also be in the FreePIE directory). 

There are no plans to add direct TrackIR support as no one on the team owns one anymore. Good luck with that and let me know if you run into any issues.

**Comment by ExtReMLapin** [comment]
I have a trackir dev kit, but the NDA is preventing me to release the source code.

**Comment by mirh** [comment]
You could hook opentrack if the official SDK is proprietary crap.

**Comment by ExtReMLapin** [comment]
There are also multiple pieces of code on github that shows reversed versions of the SDK

**Comment by mirh** [comment]
I would guess that isn't really the cleanest approach on the shed
And it would also be less flexible, assuming OT is feature complete at least.
