### ISSUE TITLE
Vertex shader using def to set matrix row

### ISSUE THREAD

**Issue by samaust** [cybereality/Perception#78]
From my understanding of how Perception works, it modifies the registers in c0-c31 using SetVertexShaderConstantF to add a translation to the projection matrix.

SetVertexShaderConstantF does not change the value of registers set by the "def" instruction.

The following vertex shader code comes from my dxgraphics18 repository.

```
// Generated by Microsoft (R) D3DX9 Shader Compiler 
//
// Parameters:
//
//   float4x4 g_mProj;
//   float4x4 g_mWorldView;
//   float3 g_vLightDirView;
//
//
// Registers:
//
//   Name            Reg   Size
//   --------------- ----- ----
//   g_mProj         c0       4
//   g_mWorldView    c4       3
//   g_vLightDirView c7       1
//
//
// Default values:
//
//   g_mProj
//     c0   = { 0, 0, 0, 0 };
//     c1   = { 0, 0, 0, 0 };
//     c2   = { 0, 0, 0, 0 };
//     c3   = { 0, 0, 0, 0 };
//
//   g_mWorldView
//     c4   = { 0, 0, 0, 0 };
//     c5   = { 0, 0, 0, 0 };
//     c6   = { 0, 0, 0, 0 };
//
//   g_vLightDirView
//     c7   = { 0, 0, -1, 0 };
//

    vs_3_0
    def c8, 1, 0, 0, 0
    dcl_position v0
    dcl_normal v1
    dcl_texcoord v2
    dcl_position o0
    dcl_color o1
    dcl_texcoord o2.xy
    dcl_texcoord1 o3.xyz
    dcl_texcoord2 o4.xyz
    mov r0.w, c8.x
    dp4 r0.x, v0, c4
    dp4 r0.y, v0, c5
    dp4 r0.z, v0, c6
    dp4 o0.x, r0, c0
    dp4 o0.y, r0, c1
    dp4 o0.z, r0, c2
    dp4 o0.w, r0, c3
    mov o4.xyz, r0
    dp3 r0.x, v1, c4
    dp3 r0.y, v1, c5
    dp3 r0.z, v1, c6
    dp3 o1, c7, r0
    mov o3.xyz, r0
    mov o2.xy, v2
```

I suppose that we only need the projection matrix in Perception. The problem in the code above is in the world-view matrix, I'm only using this code to explain what I want to explain. The same problem could happen with the projection matrix if it were designed in a similar way.

c8 is set by a "def" instruction and it's used to set the last row of the World-View matrix that has its first three rows in c4, c5, c6. Since c8 is set by "def", it can't be changed by SetVertexShaderConstantF.

* Can Perception handle a vertex shader that defines a three row matrix and uses a def for the last matrix row ? 
* Have you ever seen a game that does that ?

**Comment by EisernSchild** [comment]
Yes, Perception can handle nameless constant definitions. We, in case
Simon, already did this for "FarCry 3". He added the option to search
patterns in shaders. Watch following commit :

https://github.com/cybereality/Perception/commit/548f5604c176fe0c1fe280b3678d2ecf6f6d0811

2016-03-05 8:19 GMT+01:00 Samuel Austin <notifications@github.com>:

**Comment by samaust** [comment]
It's not an issue of changing the value of a nameless constant, it's about changing a def constant. The def hardcodes a value. From my experience, in DirectX 9, you can't change the value of such a constant with SetVertexShaderConstantF. If you wanted to change its value, you would have to change the shader code and that's possible in DirectX 9 (I don't know about 10, 11, 12).

This type of situation is probably rare, if it ever happens, as it's not a flexible way of coding shaders. I'm closing this. We'll reopen this if we ever find ourselve facing that issue.
