### ISSUE TITLE
Run my compiled Vireio perception with supported games

### ISSUE THREAD

**Issue by shunhuaiyao** [cybereality/Perception#82]
Dear All,

I'm trying to execute my compiled Vireio perception binary with supported steam games,including Left 4 dead 2 and Batman: Arkham City.
To do so, I downloaded the open source from here (Commits on Mar 21, 2016) and followed the build instructions , then compiled it in Release mode on windows8. I then copied the VRboost.dll from the official downloaded Vireio Perception 3.0.1 into my release folder(C:..\Desktop\Perception\Release\Perception\bin) and executed my compiled Vireio perception binary. Unfortunately, I still saw the 2D rendering in L4d2 and BatmanAC. However, I executed the official Vireio perception Ver 3.0.1 binary with L4d2 and BatmanAC.I could see 3D rendering in both games.

Any hints on how I may dig deeper?
Thank you very much for your helps

**Comment by shunhuaiyao** [comment]
Dear All,

I used DebugView and found there is OutputDebugString, "Aquilinus Runtime not found !", with my compiled vireio perception.exe, like this attachment.
![custom vireio](https://cloud.githubusercontent.com/assets/14013336/14064613/d5dd595e-f43b-11e5-8558-a65159206385.PNG)

Is there any steps for solving this problem?
Thank you very much.

**Comment by Enterfrize** [comment]
There is some really cool stuff in the works for Vireio Perception, but we aren't ready to reveal just yet.  Best to ignore. ;-)
Regards,Neil

**Comment by baggyg** [comment]
Although it won't be compatible with the newer stuff, if you are committed to trying to get things up and running yourself I would recommend trying an earlier commit as you base to compile. 

For example - try compiling the code as this point
https://github.com/cybereality/Perception/commit/79a1714e4e418d437e7807418be8536c7fee5730

and seeing if you have the same problems...
