### ISSUE TITLE
Host binaries on Github

### ISSUE THREAD

**Issue by Atemu** [cybereality/Perception#88]
Would it be possible to host the (pre-)release binaries here on Github?

I saw @EisernSchild recently bumped the version number to "4.0.0 Beta 1", so it'd be a good time to start doing that.

**Comment by DonFlymoor** [comment]
I agree, I can't get to the binaries on the official website, even though I'm logged in.

**Comment by Enterfrize** [comment]
Work continues...still early.

**Comment by EisernSchild** [comment]
Thx for the interest but the driver is still not useable for VR gaming .
Neither did we connect any HMD nor did we create any useable game profile
so far. It's still "core work" although advanced.

Before we publish any executable file we still need to create a detailed
tutorial on how to create game profiles using the added modification studio
"Aquilinus".

Am Do., 11. Feb. 2021 um 18:28 Uhr schrieb Enterfrize <
notifications@github.com>:
