### ISSUE TITLE
So....?

### ISSUE THREAD

**Issue by GreenMan36** [cybereality/Perception#90]
This project dead?

**Comment by baggyg** [comment]
At least for the most recent devs, yes. Its here if someone wants to continue, but we won't be.

**Comment by Enterfrize** [comment]
It's Neil from MTBS.  I'm going to catch up with the team to size this up.  I think VR has changed in a manner that is a lot less cohesive with PC gaming, and the way games are developed are changing in a way that makes solutions like Vireio Perception harder to support and develop.

The ecosystem changed, so we need to figure some things out to see how this can be pursued and if it is still reasonable to do so.

Thank you for your understanding.

**Comment by randprint** [comment]
Thanks for the work you all have put into Vireio, even if it is decided to 'stick a fork in it' it would be very wonderful of you all to finish releasing the last build, if the team is willing to open source the parts Dennis had mentioned. Thank you, still using Vireio on older games.

**Comment by EisernSchild** [comment]
Hi Guys!

There will be News here soon!

Regards, Denis


randprint <notifications@github.com> schrieb am Do., 26. Nov. 2020, 00:10:
